project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://ci-cmg.github.io/SoundscapesWebsite" 
  repo-url: "https://github.com/CI-CMG/SoundscapesWebsite"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#AABFC1"
    logo: images/onms-logo-no-text-800.png
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://sanctuaries.noaa.gov/
        text: "Office of National Marine Sanctuaries"
      - icon: github
        href: https://github.com/CI-CMG/SoundscapesWebsite
        text: "ONMS Sound"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - text: '    '
      - text: <b>East Coast Region</b>
      - href: content/sb.qmd
        text: <pre>    Stellwagen Bank</pre>
      - href: content/mb.qmd
        text: <pre>    Monterey Bay</pre>
      - href: content/oc.qmd
        text: <pre>    Olympic Coast</pre>
      - href: content/cb.qmd
        text: <pre>    Cordell Bank</pre>
      - href: content/pi.qmd
        text: <pre>    Papahānaumokuākea</pre>
      - href: https://sanctuaries.noaa.gov/science/monitoring/sound/
        text: <pre>    Project Home Page</pre>

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
